### ISSUE TITLE
GD-160: Extend `assert_array` by `do_not_contains([values ..])`

### ISSUE THREAD

**Issue by srb2thepast** [MikeSchulze/gdUnit4#160]
**The used GdUnit4 version:**

GDUnit 4.1.0

**The used Godot version:**

Godot 4.0

**OS including version:**

OS: Microsoft Windows 10 Home Version 10.0.19044 Build 19044
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: NVIDIA GeForce GTX 1660 SUPER

**Describe the bug**

Upon using `GDUnitAssert.EXPECT_FAIL` in the constructor of assert_array and passing in a scenario that instead succeeds, the assertion still passes. By the constant's name, it's expected for the assert to only pass if the result fails.

**Steps to Reproduce**

1. Create new .gdscript file with the code below
2. Debug Tests with GDUnit 4.1.0
3. Check GdUnit Console for "Expecting to fail!" and see the "PASSED" appear.

**Minimal reproduction project:**
```gdscript
class_name TestAssertArrayContains
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

func test_assert_array_contains() -> void:
	# Contains (passes)
	assert_array([1,2,3]).contains([2])
	
	# Contains with explicit expect success argument (passes) 
	assert_array([1,2,3],GdUnitAssert.EXPECT_SUCCESS).contains([2])
	
	# !!!! Contains with expect fail argument (should not pass as the array contains 2, yet still passes) 
	assert_array([1,2,3],GdUnitAssert.EXPECT_FAIL).contains([2])
	
	# Doesn't contain with expect fail argument (passes)
	assert_array([1],GdUnitAssert.EXPECT_FAIL).contains([2])
```

.zip download if preferred:
[TestAssertArrayContains.zip](https://github.com/MikeSchulze/gdUnit4/files/11140289/TestAssertArrayContains.zip)

**Comment by MikeSchulze** [comment]
Hi @srb2thepast 

The use of the "hidden" additional argument **expect_result** is not intended for the public. This argument is only used for internal test coverage to check if failed tests report the correct error message.
An assert used with **GdUnitAssert.EXPECT_FAIL** does not report the original error and only reports success unless you verify the reported message with `has_failure_message`. 

For example:
```
assert_array(null, GdUnitAssert.EXPECT_FAIL) \
		.is_not_null()\
		.has_failure_message("Expecting: not to be '<null>'")
```
This test will succeed, it expects to fail and report the error message `Expecting: not to be '<null>'`, but it will fail if the expected error message is different.

This is an expected behavior and intended for internal testing only. 

Why did you try to set this flag?

**Comment by MikeSchulze** [comment]
Yes I understand now their problem, indeed such verification is missing in assert_array. Interesting that no one else has noticed this yet.

I will convert this issue now in a feature request to extend the assert_array accordingly:
`do_not_contains([values ..])` to check if the given expected values are not contained in the current array.
