### ISSUE TITLE
GD-249: CI job failing due to missing `--headless` call

### ISSUE THREAD

**Issue by joao8545** [MikeSchulze/gdUnit4#249]
**The used GdUnit4 version:**

4.20

**The used Godot version:**

4.1.1

**OS including version:**

--

**Describe the bug**

When running the addons/gdunit4/runtest.sh in a CI pipeline it generates an error due to the first godot call inside the script not having the `--headless` command

**Steps to Reproduce**

run `addons/gdUnit4/runtest.sh  -a ./test` inside a CI pipeline

**Minimal reproduction project:**

**Comment by joao8545** [comment]
In case you see this as an actionable issue, I would be happy to work on it.

**Comment by MikeSchulze** [comment]
Hello, I am back from vacation.

This is intentional, the tests are always run without headleas mode, otherwise tests with UI interactions would not run.
You can call the script and specify Godot specific parameters with it, all parameters will be passed with the execution, it is not necessary to change the existing script.

`--headless` is an exception here the displayed error should be understandable enough.
![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/834e6bec-bc95-44c3-8d4d-ff45cf185e84)


Can you describe the error message you get?

**Comment by MikeSchulze** [comment]
I close this issue now because of no updates here.
