### ISSUE TITLE
GD-298: Installing GdUnit4 causes Godot to start reporting node / resource leaks

### ISSUE THREAD

**Issue by voithos** [MikeSchulze/gdUnit4#298]
**The used GdUnit4 version:**
4.2.0

**The used Godot version:**
4.2.1

**OS including version:**
Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.2849) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

**Describe the bug**
I just installed GdUnit4 in my Godot4 project, and without having done anything else, noticed that I started getting node/resource leak notifications when closing the editor. Disabling the plugin causes the messages to go away.

Here's a Gist with the output text, including leak references: https://gist.github.com/voithos/2d99bfadfd06f4ef9fd807dc4922a22d

**Steps to Reproduce**
1. Create a new Godot 4.2.1 project
2. Install and enable GdUnit4
3. Observe the errors when closing the editor

**Minimal reproduction project:**
N/A

**Comment by MikeSchulze** [comment]
Hi, thanks for reporting.

This is a Godot engine related bug.
I spend a lot of time to reduce it to a single orphan file error for better understanding what goes wrong here.

I used static functions to simplify calls like this
```
class_name Orphan
extends RefCounted


static func success() -> Orphan:
	var result = Orphan.new()
	return result
```
To call it like `var o:= Orphan.success()`

Then I tested against various Godot builds, and it's been broken since `Godot v4.2.dev3.official.013e8e3af`
```
v4.2.dev1.official.0c2144da9 - ok
v4.2.dev2.official.da81ca62a - ok
v4.2.dev3.official.013e8e3af- orphans
v4.2.dev4.official.549fcce5f- orphans
v4.2.dev6.official.57a6813bb - orphans
v4.2.beta1.official.b1371806a - orphans
v4.2.beta4.official.93cdacbb0 - orphans
v4.2.rc1.official.ad72de508 - orphans
v4.2.stable.official.46dc27791 - orphans
```

I will prepare tomorrow an issue on Godot to report this memory leak issue.

**Comment by voithos** [comment]
I see, thanks for the thorough investigation!

**Comment by MikeSchulze** [comment]
I have reported this problem to [godotengine](https://github.com/godotengine/godot/issues/86540), and until then there is nothing I can do about it and therefore close this topic in the clarified form.
