### ISSUE TITLE
GD-312: Mocks produce code that fails when project has "warn as error" enabled for inferred types

### ISSUE THREAD

**Issue by dreed-sd** [MikeSchulze/gdUnit4#312]
**The used GdUnit4 version:**
4.2.1

**The used Godot version:**
4.2 stable

**OS including version:**
MacOS

**Describe the bug**
When a test uses mock(), temporary code is generated. The generated code is subject to the host project's "warn as error" settings, so is likely to fail to parse if the host project has any non-default settings. Project warning rules are not supposed to apply to addons with the "ignore addons" setting, however the generated code is in "tmp" and not nested inside "addons", so it is not considered addon code.

**Steps to Reproduce**
1. Create an empty project and install gdunit4
2. In project settings, set Debug->GDScript->Untyped Declaration to `Error`
3. Write a gdunit test that uses mock()
4. Run the test
5. --> Generated mock code produces an error and the test cannot run

**Comment by dreed-sd** [comment]
Related to this is a Godot bug where 'warn as error' applies to addons when using command-line tools: https://github.com/godotengine/godot/issues/87094

**Comment by MikeSchulze** [comment]
Thanks for reporting this, I can reproduce it.

I need a deeper investigation to solve this, the GdUnit4 plugin is compatible with Godot 4.1.x and there are many changes since the type support is implemented.
Important is do not set `debug/gdscript/warnings/exclude_addons=false` and `debug/gdscript/warnings/untyped_declaration=Error`, these are unsolvable problems due to backward compability
