### ISSUE TITLE
GD-356: simulate_mouse_move_relative throws an exception

### ISSUE THREAD

**Issue by bugbountyguy** [MikeSchulze/gdUnit4#356]
### The used GdUnit4 version

4.2.0 (Latest Release)

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Linux Mint 21.3

### Describe the bug

I have a test case that needs to use the simulation for mouse_move_relative, and I was following the instructions here:
https://mikeschulze.github.io/gdUnit4/advanced_testing/sceneRunner/#simulate_mouse_move_relative

Here's my code snippet:
```
	var runner = scene_runner("res://test/scenes/test_player_scene.tscn")
	var player = runner.invoke("find_child", "1")
	await assert_func(player, "is_on_floor").wait_until(500).is_true()
	runner.simulate_mouse_move_relative(Vector2(100, 100), 1.0)
```
However, the `simulate_mouse_move_relative` keeps throwing several exceptions, with this one being on the top of the list:
```
	'at: GdUnitSceneRunnerImpl.get_mouse_position (res://addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd:137)'
Error: 'Cannot call method 'get_viewport' on a null value.'
```
Is there an instruction I'm missing by chance, or is this a bug? My scene definitely loads and I can see my character in the scene. Other tests work fine, such as moving onto blocks and all that stuff... Any help would be appreciated!

### Steps to Reproduce

(see bug information above - just make a test similar to that)

**Comment by MikeSchulze** [comment]
Thanks for reporting.

The `get_viewport` should be work when the scene is successfully loaded, I will have a look what is broken.

**Comment by MikeSchulze** [comment]
Update!
The cause is that the scene is released when the test is finished, but the `simulate_mouse_move_relative` still tries to wait for the next frame of the scene.
The missing `await` on `simulate_mouse_move_relative` results in the test, not waiting until the mouse move is finished.

I have updated the inline documentation to point this out more clearly, and have also made the scene runner more robust against such exceptions.
